import type { Metadata } from "next";
import { Roboto } from "next/font/google"; // Import Roboto font
import "./globals.css";

// Roboto font configuration
const roboto = Roboto({
  weight: ["100", "400", "700"], // Add multiple weights if needed
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-[#FFFFFF]`}>
        {/* Apply the Roboto font to the entire body */}
        {children}
      </body>
    </html>
  );
}
